site_name: "${{values.team}}-${{values.application_id}}-deploy"
site_description: "Deployment documentation for ${{values.team}}-${{values.application_id}}"

nav:
  - Introduction: index.md

plugins:
  - techdocs-core
