# Dev environment overrides
replicaCount: 1

resources:
  requests:
    memory: "32Mi"
    cpu: "50m"
  limits:
    memory: "64Mi"
    cpu: "100m"

ingress:
  className: "nginx-tietoevry"
  hosts:
    - host: ${{values.team}}-${{values.application_id}}.dev.${{values.fqdn}}
  tls:
    enabled: true
    hosts: ${{values.team}}-${{values.application_id}}.dev.${{values.fqdn}}
    secretName: ${{values.team}}-${{values.application_id}}-dev-tls
