# Prod environment overrides
replicaCount: 1

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"


ingress:
  className: "nginx-tietoevry"
  hosts:
    - host: ${{values.team}}-${{values.application_id}}.prod.${{values.fqdn}}
  tls:
    enabled: true
    hosts: ${{values.team}}-${{values.application_id}}.prod.${{values.fqdn}}
    secretName: ${{values.team}}-${{values.application_id}}-prod-tls