site_name: "${{values.team}}-${{values.application_id}}-dev"
site_description: "Development documentation for ${{values.team}}-${{values.application_id}}"

nav:
  - Introduction: index.md

plugins:
  - techdocs-core
